// Forklift Pre-Delivery Inspection template
// sections: ordered list of check items for this vehicle type
// each item: { id, label, na_for: [] }
// na_for: vehicle subtypes where this item is N/A (e.g. 'FORKLIFT_ELECTRIC')
export const template = {
  type: 'PDI',
  vehicle: 'FORKLIFT',
  title: 'Forklift Delivery Inspection / 叉车交付检查报告',

  sections: [

    {
      id: 'basic_info',
      label: 'Basic Information / 基本信息',
      has_result: false,
      na_for: [],
      fields: [
        'customer', 'invoice_number', 'machine_type', 'model',
        'serial_number', 'hour_meter', 'date', 'technician', 'location',
      ],
    },

    {
      id: 'attachment_accessories',
      label: 'Attachment & Accessories / 附件与配件检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'att_side_shift',       label: 'Side Shift / 侧移器',                              conditional: true },
        { id: 'att_positioner',       label: 'Positioner / 调距器',                              conditional: true },
        { id: 'att_forks',            label: 'Forks / 货叉',                                     na_for: [] },
        { id: 'att_charger',          label: 'Charger / 充电器',                                 na_for: ['FORKLIFT_ICE'] },
        { id: 'att_keys',             label: 'Keys checked / 钥匙已检查',                        na_for: [] },
        { id: 'att_operator_manual',  label: 'Operator manual / 操作手册',                       na_for: [] },
        { id: 'att_service_manual',   label: 'Service manual if supplied / 维修手册',            na_for: [] },
        { id: 'att_charger_check',    label: 'Charger checked if supplied / 充电器已检查',       na_for: ['FORKLIFT_ICE'] },
        { id: 'att_condition',        label: 'Attachment condition / 附件状态',                   na_for: [] },
        { id: 'att_matches_order',    label: 'Confirmed matches order / 确认与订单一致',          na_for: [] },
      ],
    },

    {
      id: 'visual_structure',
      label: 'Visual & Structure Inspection / 外观与结构检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'vs_body_panels',    label: 'Body panels and covers / 车身外板护盖',              na_for: [] },
        { id: 'vs_paint',          label: 'Paint condition and appearance / 漆面外观',           na_for: [] },
        { id: 'vs_chassis',        label: 'Chassis / frame — cracks, deformation / 底盘车架',   na_for: [] },
        { id: 'vs_overhead_guard', label: 'Overhead guard / canopy / 护顶架',                   na_for: ['FORKLIFT_WALKIE'] },
        { id: 'vs_seat',           label: 'Seat, pedals, handles, operator area / 座椅踏板',    na_for: [] },
        { id: 'vs_decals',         label: 'Safety decals and warning signs / 安全标识',          na_for: [] },
        { id: 'vs_covers',         label: 'Covers and guards secured / 护板盖板固定',            na_for: [] },
        { id: 'vs_wiring_routing', label: 'Wiring harness routing / 线束走向',                  na_for: [] },
      ],
    },

    {
      id: 'fluid_levels',
      label: 'Fluid Level & Leak Inspection / 油液液位与泄漏检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'fl_engine_oil',   label: 'Engine oil level / 发动机机油',                na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'fl_coolant',      label: 'Coolant level / 冷却液',                       na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'fl_hydraulic',    label: 'Hydraulic oil level / 液压油',                 na_for: [] },
        { id: 'fl_brake_fluid',  label: 'Brake fluid / 刹车油',                        na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'fl_transmission', label: 'Transmission oil / 变速箱油',                  na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'fl_diff_oil',     label: 'Differential oil / 差速器油',                  na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'fl_fuel',         label: 'Fuel level / 燃油液位',                        na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'fl_leak_engine',  label: 'Engine oil leaks / 机油泄漏',                  na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'fl_leak_coolant', label: 'Coolant leaks / 冷却液泄漏',                   na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'fl_leak_hyd',     label: 'Hydraulic oil leaks / 液压油泄漏',             na_for: [] },
        { id: 'fl_leak_trans',   label: 'Transmission / axle leaks / 变速箱车桥泄漏',   na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
      ],
    },

    {
      id: 'engine_mechanical',
      label: 'Engine & Mechanical Inspection / 发动机与机械检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'],
      items: [
        { id: 'em_starting',    label: 'Engine starting condition / 启动状态' },
        { id: 'em_idle',        label: 'Idle condition / 怠速状态' },
        { id: 'em_accel',       label: 'Acceleration response / 加速响应' },
        { id: 'em_noise',       label: 'Abnormal engine noise / 异常噪音' },
        { id: 'em_smoke',       label: 'Abnormal smoke / 异常冒烟' },
        { id: 'em_cooling_fan', label: 'Cooling fan and radiator / 冷却风扇水箱' },
        { id: 'em_belt',        label: 'Belt condition / 皮带状态' },
        { id: 'em_air_filter',  label: 'Air filter condition / 空气滤芯' },
        { id: 'em_exhaust',     label: 'Exhaust system / 排气系统' },
        { id: 'em_mounts',      label: 'Engine mounts / 发动机机脚' },
      ],
    },

    {
      id: 'electrical_system',
      label: 'Electrical System & Controller / 电气系统与控制器检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'es_battery',           label: 'Battery condition / 电池状态',                              na_for: [] },
        { id: 'es_battery_terminals', label: 'Battery terminals and main connections / 电池端子主电源',   na_for: [] },
        { id: 'es_charger_conn',      label: 'Charger connection / 充电器连接',                          na_for: ['FORKLIFT_ICE'] },
        { id: 'es_dcdc',              label: 'DC/DC converter / DC/DC转换器',                            na_for: ['FORKLIFT_ICE'] },
        { id: 'es_lights_horn',       label: 'Lights, horn, beacon, reverse alarm / 灯光喇叭警示',       na_for: [] },
        { id: 'es_dashboard',         label: 'Dashboard / display / 仪表显示屏',                         na_for: [] },
        { id: 'es_warnings',          label: 'Warning lights and error display / 报警灯故障显示',         na_for: [] },
        { id: 'es_wiring',            label: 'Wiring harness and connectors / 线束插头',                 na_for: [] },
        { id: 'es_curtis_history',    label: 'Curtis — fault history / 故障历史',                       na_for: ['FORKLIFT_ICE'] },
        { id: 'es_curtis_active',     label: 'Curtis — active fault codes / 当前故障码',                 na_for: ['FORKLIFT_ICE'] },
        { id: 'es_curtis_cleared',    label: 'Curtis — codes cleared if required / 故障码已清除',        na_for: ['FORKLIFT_ICE'] },
        { id: 'es_curtis_final',      label: 'Curtis — no active faults after final test / 最终无故障',  na_for: ['FORKLIFT_ICE'] },
      ],
    },

    {
      id: 'hydraulic_system',
      label: 'Hydraulic System Inspection / 液压系统检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'hy_pump',       label: 'Hydraulic pump operation / 液压泵工作状态',          na_for: [] },
        { id: 'hy_hoses',      label: 'Hose condition and position / 油管状态位置',          na_for: [] },
        { id: 'hy_fittings',   label: 'Fittings and connections / 液压接头',                na_for: [] },
        { id: 'hy_cylinders',  label: 'Cylinders — damage and leaks / 油缸损伤泄漏',        na_for: [] },
        { id: 'hy_lift_lower', label: 'Lift and lowering function / 起升下降功能',          na_for: [] },
        { id: 'hy_tilt',       label: 'Tilt forward and backward / 前倾后倾功能',            na_for: [] },
        { id: 'hy_side_shift', label: 'Side shift function if fitted / 侧移功能',           conditional: true },
        { id: 'hy_positioner', label: 'Positioner function if fitted / 调距器功能',         conditional: true },
        { id: 'hy_attachment', label: 'Attachment hydraulic function if fitted / 附件液压',  conditional: true },
        { id: 'hy_valve_leak', label: 'Control valve / multi-way valve leaks / 多路阀泄漏', na_for: [] },
        { id: 'hy_drift',      label: 'Hydraulic drift or abnormal pressure loss / 液压下沉', na_for: [] },
      ],
    },

    {
      id: 'mast_fork_chain',
      label: 'Mast, Fork & Chain Inspection / 门架、货叉与链条检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'mf_mast_structure',  label: 'Mast structure and rollers / 门架结构滚轮',      na_for: [] },
        { id: 'mf_mast_travel',     label: 'Mast full travel / 门架全行程',                  na_for: [] },
        { id: 'mf_chain_condition', label: 'Lift chains condition / 起升链条状态',            na_for: [] },
        { id: 'mf_chain_tension',   label: 'Chain tension and adjustment / 链条张紧度',       na_for: [] },
        { id: 'mf_lube',            label: 'Mast and chains lubricated / 门架链条润滑',       na_for: [] },
        { id: 'mf_fork_condition',  label: 'Fork arms condition / 货叉状态',                  na_for: [] },
        { id: 'mf_fork_heels',      label: 'Fork heels — excessive wear / 货叉根部磨损',      na_for: [] },
        { id: 'mf_fork_tips',       label: 'Fork tips — damage or deformation / 货叉尖端',    na_for: [] },
        { id: 'mf_fork_pins',       label: 'Fork locking pins / 货叉锁销',                   na_for: [] },
        { id: 'mf_carriage',        label: 'Carriage and fork mounting area / 叉架安装',      na_for: [] },
      ],
    },

    {
      id: 'steering_brake_dynamic',
      label: 'Steering, Brake & Dynamic Test / 转向、刹车与动态测试',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'sb_travel',            label: 'Forward and reverse travel / 前进后退',                   na_for: [] },
        { id: 'sb_acceleration',      label: 'Starting acceleration / 起步加速',                        na_for: [] },
        { id: 'sb_low_speed',         label: 'Low-speed control / 低速控制',                            na_for: [] },
        { id: 'sb_service_brake',     label: 'Service brake performance / 行车刹车',                    na_for: [] },
        { id: 'sb_parking_brake',     label: 'Parking brake performance / 驻车刹车',                    na_for: [] },
        { id: 'sb_emergency_stop',    label: 'Emergency stop if fitted / 急停功能',                    conditional: true },
        { id: 'sb_steering',          label: 'Steering operation / 转向功能',                           na_for: [] },
        { id: 'sb_steering_freeplay', label: 'Steering wheel free play / 方向盘自由间隙',               na_for: [] },
        { id: 'sb_steering_hose',     label: 'Power steering hoses for leaks / 助力油管泄漏',           na_for: [] },
        { id: 'sb_steering_pump',     label: 'Steering pump / motor noise / 转向泵电机噪音',            na_for: [] },
        { id: 'sb_regen',             label: 'Regenerative braking / 再生制动',                         na_for: ['FORKLIFT_ICE'] },
        { id: 'sb_ctrl_response',     label: 'Controller response accel/decel / 控制器响应',            na_for: ['FORKLIFT_ICE'] },
        { id: 'sb_noise_vibration',   label: 'Abnormal noise, vibration / 异常噪音振动',                na_for: [] },
        { id: 'sb_brake_pedal',       label: 'Brake pedal pressure / master cylinder / 刹车踏板保压',   na_for: [] },
        { id: 'sb_pedal_sink',        label: 'Pedal does not slowly sink / 踏板不下沉',                 na_for: [] },
      ],
    },

    {
      id: 'tyre_wheel',
      label: 'Tyre & Wheel Inspection / 轮胎与车轮检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'tw_condition', label: 'Tyre condition / 轮胎状态',                      na_for: [] },
        { id: 'tw_pressure',  label: 'Tyre pressure / 胎压',                           na_for: [] },
        { id: 'tw_wear',      label: 'Tyre wear / 轮胎磨损',                           na_for: [] },
        { id: 'tw_damage',    label: 'Cuts, cracks or sidewall damage / 割伤裂纹侧壁', na_for: [] },
        { id: 'tw_rims',      label: 'Wheel rims condition / 轮毂状态',                na_for: [] },
        { id: 'tw_nuts',      label: 'Wheel nuts / bolts / 车轮螺母螺栓',              na_for: [] },
        { id: 'tw_torque',    label: 'Wheel nut torque / 螺丝扭矩',                    na_for: [] },
        { id: 'tw_marking',   label: 'Wheel nuts marked if required / 螺丝标记',       conditional: true },
      ],
    },

    {
      id: 'safety_functions',
      label: 'Safety Function Inspection / 安全功能检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'sf_seat_switch',      label: 'Seat switch if fitted / 座椅开关',            conditional: true },
        { id: 'sf_neutral_safety',   label: 'Neutral safety if fitted / 空档保护',          conditional: true },
        { id: 'sf_travel_interlock', label: 'Travel interlock if fitted / 行驶联锁',        conditional: true },
        { id: 'sf_hyd_interlock',    label: 'Hydraulic interlock if fitted / 液压联锁',     conditional: true },
        { id: 'sf_horn',             label: 'Horn / 喇叭',                                  na_for: [] },
        { id: 'sf_reverse_alarm',    label: 'Reverse alarm / 倒车蜂鸣器',                   na_for: [] },
        { id: 'sf_beacon',           label: 'Beacon / warning light / 警示灯',              na_for: [] },
        { id: 'sf_mirrors',          label: 'Mirrors and camera if fitted / 后视镜摄像头',  conditional: true },
        { id: 'sf_emergency_stop',   label: 'Emergency stop if fitted / 急停开关',          conditional: true },
        { id: 'sf_parking_warning',  label: 'Parking brake warning if fitted / 驻车报警',   conditional: true },
      ],
    },

    {
      id: 'maintenance_work',
      label: 'Maintenance Work Completed / 已完成保养项目',
      has_result: false,
      na_for: [],
      items: [
        { id: 'mw_engine_oil_change',  label: 'Engine oil changed / 已更换机油',                   na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_oil_filter',         label: 'Engine oil filter changed / 已更换机油滤芯',         na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_air_filter_clean',   label: 'Air filter cleaned / 已清理空气滤芯',               na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_air_filter_replace', label: 'Air filter replaced / 已更换空气滤芯',               na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_hydraulic_oil',      label: 'Hydraulic oil topped up / changed / 液压油',         na_for: [] },
        { id: 'mw_hydraulic_filter',   label: 'Hydraulic filter replaced if required / 液压滤芯',   na_for: [] },
        { id: 'mw_transmission',       label: 'Transmission fluid changed / topped up / 变速箱油',  na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'mw_trans_filter',       label: 'Transmission filter if required / 变速箱滤芯',       na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'mw_fuel_filter',        label: 'Fuel filter if required / 燃油滤芯',                na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_water_sep',          label: 'Water separator checked / drained / 油水分离器',     na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_coolant',            label: 'Coolant topped up / 已添加冷却液',                   na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_brake_fluid',        label: 'Brake fluid checked / topped up / 刹车油',           na_for: ['FORKLIFT_WALKIE'], model_dependent: ['FORKLIFT_ELECTRIC'] },
        { id: 'mw_fuel_level',         label: 'Fuel level checked / 燃油液位',                      na_for: ['FORKLIFT_ELECTRIC', 'FORKLIFT_WALKIE'] },
        { id: 'mw_grease_nipples',     label: 'Grease nipples checked before greasing / 黄油嘴检查', na_for: [] },
        { id: 'mw_grease',             label: 'Grease points serviced / 已加注黄油点',               na_for: [] },
        { id: 'mw_mast_lube',          label: 'Mast lubricated / 已润滑门架',                       na_for: [] },
        { id: 'mw_chain_lube',         label: 'Chains lubricated and adjusted / 已润滑链条',         na_for: [] },
        { id: 'mw_tyre_pressure',      label: 'Tyre pressure checked / 已检查胎压',                  na_for: [] },
        { id: 'mw_wheel_torque',       label: 'Wheel nut torque checked / 已检查轮胎螺丝扭矩',       na_for: [] },
        { id: 'mw_curtis',             label: 'Curtis fault history checked / Curtis控制器检查',     na_for: ['FORKLIFT_ICE'] },
        { id: 'mw_test_drive',         label: 'Test drive completed / 已完成试车',                   na_for: [] },
      ],
    },

    {
      id: 'issues_found',
      label: 'Issues Found & Action Taken / 发现问题与处理措施',
      has_result: false,
      na_for: [],
      // 动态数组，每条 issue:
      // { description: string, action_taken: string, status: 'completed' | 'pending' | 'monitor' | 'quoted' }
    },

    {
      id: 'final_result',
      label: 'Final Test Result / 最终测试结果',
      has_result: false,
      na_for: [],
      items: [
        { id: 'fr_static',    label: 'Static inspection completed / 静态检查已完成' },
        { id: 'fr_dynamic',   label: 'Dynamic test completed / 动态测试已完成' },
        { id: 'fr_functions', label: 'All major functions tested / 主要功能均已测试' },
        { id: 'fr_ok',        label: 'Machine tested and functional / 车辆测试功能正常' },
        { id: 'fr_no_faults', label: 'No active faults after final test / 最终测试后无故障' },
      ],
      final_fields: ['ready_for_delivery', 'final_comments', 'technician', 'date', 'signature'],
    },

  ],
};
