// Loader/Skid Steer Pre-Delivery Inspection template
export const template = {
  type: 'PDI',
  vehicle: 'LOADER',
  title: 'Wheel Loader Delivery Inspection / 装载机交付检查报告',

  sections: [

    {
      id: 'basic_info',
      label: 'Basic Information / 基本信息',
      has_result: false,
      na_for: [],
      fields: ['customer', 'invoice_number', 'machine_type', 'model', 'serial_number', 'hour_meter', 'date', 'technician', 'location'],
    },

    {
      id: 'attachment_accessories',
      label: 'Attachment & Accessories / 附件与配件检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'att_gp_bucket',       label: 'GP Bucket / 通用铲斗',                            conditional: true },
        { id: 'att_4in1_bucket',     label: '4 in 1 Bucket / 四合一铲斗',                      conditional: true },
        { id: 'att_pallet_fork',     label: 'Pallet Fork / 托盘叉',                            conditional: true },
        { id: 'att_keys',            label: 'Keys checked / 钥匙已检查',                        na_for: [] },
        { id: 'att_operator_manual', label: 'Operator manual / 操作手册',                       na_for: [] },
        { id: 'att_service_manual',  label: 'Service manual if supplied / 维修手册',            na_for: [] },
        { id: 'att_condition',       label: 'Attachment condition / 附件状态',                   na_for: [] },
        { id: 'att_matches_order',   label: 'Confirmed matches order / 确认与订单一致',          na_for: [] },
      ],
    },

    {
      id: 'visual_structure',
      label: 'Visual & Structure Inspection / 外观与结构检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'vs_body_panels',    label: 'Body panels and covers / 车身外板护盖',              na_for: [] },
        { id: 'vs_paint',          label: 'Paint condition and appearance / 漆面外观',           na_for: [] },
        { id: 'vs_chassis',        label: 'Chassis / frame — cracks, deformation / 底盘车架',   na_for: [] },
        { id: 'vs_cabin',          label: 'Cabin / canopy condition / 驾驶室顶棚',              na_for: [] },
        { id: 'vs_seat',           label: 'Seat, pedals, handles, operator area / 座椅踏板',    na_for: [] },
        { id: 'vs_decals',         label: 'Safety decals and warning signs / 安全标识',          na_for: [] },
        { id: 'vs_covers',         label: 'Covers and guards secured / 护板盖板固定',            na_for: [] },
        { id: 'vs_wiring_routing', label: 'Wiring harness routing / 线束走向',                  na_for: [] },
      ],
    },

    {
      id: 'fluid_levels',
      label: 'Fluid Level & Leak Inspection / 油液液位与泄漏检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'fl_engine_oil',   label: 'Engine oil level / 发动机机油',                na_for: [] },
        { id: 'fl_coolant',      label: 'Coolant level / 冷却液',                       na_for: [] },
        { id: 'fl_hydraulic',    label: 'Hydraulic oil level / 液压油',                 na_for: [] },
        { id: 'fl_brake_fluid',  label: 'Brake fluid if applicable / 刹车油',           conditional: true },
        { id: 'fl_transmission', label: 'Transmission oil / 变速箱油',                  na_for: [] },
        { id: 'fl_front_axle',   label: 'Front axle oil if applicable / 前桥油',        conditional: true },
        { id: 'fl_rear_axle',    label: 'Rear axle oil if applicable / 后桥油',         conditional: true },
        { id: 'fl_fuel',         label: 'Fuel level / 燃油液位',                        na_for: [] },
        { id: 'fl_leak_engine',  label: 'Engine oil leaks / 机油泄漏',                  na_for: [] },
        { id: 'fl_leak_coolant', label: 'Coolant leaks / 冷却液泄漏',                   na_for: [] },
        { id: 'fl_leak_hyd',     label: 'Hydraulic oil leaks / 液压油泄漏',             na_for: [] },
        { id: 'fl_leak_trans',   label: 'Transmission / axle leaks / 变速箱车桥泄漏',   na_for: [] },
      ],
    },

    {
      id: 'engine_mechanical',
      label: 'Engine & Mechanical Inspection / 发动机与机械检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'em_starting',    label: 'Engine starting condition / 启动状态' },
        { id: 'em_idle',        label: 'Idle condition / 怠速状态' },
        { id: 'em_accel',       label: 'Acceleration response / 加速响应' },
        { id: 'em_noise',       label: 'Abnormal engine noise / 异常噪音' },
        { id: 'em_smoke',       label: 'Abnormal smoke / 异常冒烟' },
        { id: 'em_cooling_fan', label: 'Cooling fan and radiator / 冷却风扇水箱' },
        { id: 'em_engine_belt', label: 'Engine belt condition / 发动机皮带' },
        { id: 'em_alt_belt',    label: 'Alternator belt condition / 发电机皮带' },
        { id: 'em_comp_belt',   label: 'Air compressor belt if fitted / 空压机皮带',  conditional: true },
        { id: 'em_ac_belt',     label: 'A/C belt if fitted / 空调皮带',               conditional: true },
        { id: 'em_air_filter',  label: 'Air filter condition / 空气滤芯' },
        { id: 'em_exhaust',     label: 'Exhaust system / 排气系统' },
        { id: 'em_mounts',      label: 'Engine mounts / 发动机机脚' },
      ],
    },

    {
      id: 'electrical_system',
      label: 'Electrical System Inspection / 电气系统检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'es_battery',           label: 'Battery condition / 电池状态' },
        { id: 'es_battery_terminals', label: 'Battery terminals and connections / 电池端子主电源' },
        { id: 'es_alternator',        label: 'Alternator charging condition / 发电机充电状态',    conditional: true },
        { id: 'es_lights_horn',       label: 'Lights, horn, beacon, reverse alarm / 灯光喇叭警示' },
        { id: 'es_dashboard',         label: 'Dashboard / display / 仪表显示屏' },
        { id: 'es_warnings',          label: 'Warning lights and error display / 报警灯故障显示' },
        { id: 'es_wiring',            label: 'Wiring harness and connectors / 线束插头' },
        { id: 'es_camera',            label: 'Camera and monitor if fitted / 摄像头显示器',       conditional: true },
      ],
    },

    {
      id: 'hydraulic_system',
      label: 'Hydraulic System Inspection / 液压系统检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'hy_pump',        label: 'Hydraulic pump operation / 液压泵工作状态' },
        { id: 'hy_hoses',       label: 'Hose condition and position / 油管状态位置' },
        { id: 'hy_fittings',    label: 'Fittings and connections / 液压接头' },
        { id: 'hy_cylinders',   label: 'Cylinders — damage and leaks / 油缸损伤泄漏' },
        { id: 'hy_arm_lift',    label: 'Loader arm lift and lowering / 大臂起升下降' },
        { id: 'hy_bucket_tilt', label: 'Bucket tilt / dump / crowd / 铲斗前翻后收' },
        { id: 'hy_4in1',        label: '4 in 1 bucket function if fitted / 四合一铲斗功能', conditional: true },
        { id: 'hy_pallet_fork', label: 'Pallet fork function if fitted / 托盘叉功能',       conditional: true },
        { id: 'hy_valve_leak',  label: 'Control valve / multi-way valve leaks / 多路阀泄漏' },
        { id: 'hy_drift',       label: 'Hydraulic drift or abnormal pressure loss / 液压下沉' },
      ],
    },

    {
      id: 'loader_arm_axle',
      label: 'Loader Axle, Mounting & Attachment / 车桥、固定件与附件检查',
      has_result: true,
      result_options: ['OK', 'NG', 'N/A'],
      na_for: [],
      items: [
        { id: 'la_front_axle',       label: 'Front axle condition / 前桥状态' },
        { id: 'la_rear_axle',        label: 'Rear axle condition / 后桥状态' },
        { id: 'la_front_axle_bolts', label: 'Front axle mounting bolts / 前桥固定螺丝' },
        { id: 'la_rear_axle_bolts',  label: 'Rear axle mounting bolts / 后桥固定螺丝' },
        { id: 'la_engine_mounts',    label: 'Engine mount condition / 发动机机脚' },
        { id: 'la_engine_bolts',     label: 'Engine mount bolts / 发动机机脚固定螺丝' },
        { id: 'la_arm_condition',    label: 'Loader arm condition / 大臂状态' },
        { id: 'la_arm_pins',         label: 'Loader arm pins and bushes / 大臂销轴衬套' },
        { id: 'la_bucket_pins',      label: 'Bucket / attachment locking pins / 铲斗附件锁销' },
        { id: 'la_bucket_op',        label: 'Bucket operation / 铲斗动作' },
        { id: 'la_attachment_op',    label: 'Pallet fork / 4 in 1 / attachment operation if fitted / 附件功能', conditional: true },
      ],
    },

    {
      id: 'steering_brake_dynamic',
      label: 'Steering, Brake & Dynamic Test / 转向、刹车与动态测试',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'sb_travel',            label: 'Forward and reverse travel / 前进后退' },
        { id: 'sb_acceleration',      label: 'Starting acceleration / 起步加速' },
        { id: 'sb_low_speed',         label: 'Low-speed control / 低速控制' },
        { id: 'sb_gear_selection',    label: 'Gear selection / transmission response / 档位变速箱响应' },
        { id: 'sb_service_brake',     label: 'Service brake performance / 行车刹车' },
        { id: 'sb_parking_brake',     label: 'Parking brake performance / 驻车刹车' },
        { id: 'sb_emergency_stop',    label: 'Emergency stop if fitted / 急停功能', conditional: true },
        { id: 'sb_steering',          label: 'Steering operation / 转向功能' },
        { id: 'sb_steering_freeplay', label: 'Steering wheel free play / 方向盘自由间隙' },
        { id: 'sb_steering_hose',     label: 'Power steering hoses for leaks / 助力油管泄漏' },
        { id: 'sb_steering_pump',     label: 'Steering pump noise / 转向泵噪音' },
        { id: 'sb_noise_vibration',   label: 'Abnormal noise, vibration / 异常噪音振动' },
        { id: 'sb_brake_pedal',       label: 'Brake pedal pressure / booster / 刹车踏板保压助力器' },
        { id: 'sb_pedal_sink',        label: 'Pedal does not slowly sink / 踏板不下沉' },
      ],
    },

    {
      id: 'tyre_wheel',
      label: 'Tyre & Wheel Inspection / 轮胎与车轮检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'tw_condition', label: 'Tyre condition / 轮胎状态' },
        { id: 'tw_pressure',  label: 'Tyre pressure / 胎压' },
        { id: 'tw_wear',      label: 'Tyre wear / 轮胎磨损' },
        { id: 'tw_damage',    label: 'Cuts, cracks or sidewall damage / 割伤裂纹侧壁' },
        { id: 'tw_rims',      label: 'Wheel rims condition / 轮毂状态' },
        { id: 'tw_nuts',      label: 'Wheel nuts / bolts / 车轮螺母螺栓' },
        { id: 'tw_torque',    label: 'Wheel nut torque / 螺丝扭矩' },
        { id: 'tw_marking',   label: 'Wheel nuts marked if required / 螺丝标记', conditional: true },
      ],
    },

    {
      id: 'safety_functions',
      label: 'Safety Function Inspection / 安全功能检查',
      has_result: true,
      result_options: ['OK', 'NG'],
      na_for: [],
      items: [
        { id: 'sf_seat_belt',      label: 'Seat belt condition / 安全带状态' },
        { id: 'sf_neutral_safety', label: 'Neutral safety if fitted / 空档保护', conditional: true },
        { id: 'sf_horn',           label: 'Horn / 喇叭' },
        { id: 'sf_reverse_alarm',  label: 'Reverse alarm / 倒车蜂鸣器' },
        { id: 'sf_beacon',         label: 'Beacon / warning light / 警示灯' },
        { id: 'sf_mirrors',        label: 'Mirrors and camera if fitted / 后视镜摄像头', conditional: true },
      ],
    },

    {
      id: 'maintenance_work',
      label: 'Maintenance Work Completed / 已完成保养项目',
      has_result: false,
      na_for: [],
      items: [
        { id: 'mw_engine_oil_change',  label: 'Engine oil changed / 已更换机油' },
        { id: 'mw_oil_filter',         label: 'Engine oil filter changed / 已更换机油滤芯' },
        { id: 'mw_air_filter_clean',   label: 'Air filter cleaned / 已清理空气滤芯' },
        { id: 'mw_air_filter_replace', label: 'Air filter replaced / 已更换空气滤芯' },
        { id: 'mw_hydraulic_oil',      label: 'Hydraulic oil topped up / changed / 液压油' },
        { id: 'mw_hydraulic_filter',   label: 'Hydraulic filter replaced if required / 液压滤芯' },
        { id: 'mw_transmission',       label: 'Transmission fluid changed / topped up / 变速箱油' },
        { id: 'mw_trans_filter',       label: 'Transmission filter replaced if required / 变速箱滤芯' },
        { id: 'mw_fuel_filter',        label: 'Fuel filter replaced if required / 燃油滤芯' },
        { id: 'mw_water_sep',          label: 'Water separator checked / drained / 油水分离器' },
        { id: 'mw_coolant',            label: 'Coolant topped up / 已添加冷却液' },
        { id: 'mw_brake_fluid',        label: 'Brake fluid checked / topped up / 刹车油' },
        { id: 'mw_fuel_level',         label: 'Diesel / fuel level checked / 燃油液位' },
        { id: 'mw_axle_oil',           label: 'Front and rear diff oil checked / topped up / 前后桥油' },
        { id: 'mw_grease_nipples',     label: 'Grease nipples checked before greasing / 黄油嘴检查' },
        { id: 'mw_grease',             label: 'Grease points serviced / 已加注黄油点' },
        { id: 'mw_arm_pins_grease',    label: 'Loader arm and bucket pins greased / 大臂铲斗销轴润滑' },
        { id: 'mw_tyre_pressure',      label: 'Tyre pressure checked / 已检查胎压' },
        { id: 'mw_wheel_torque',       label: 'Wheel nut torque checked / 已检查轮胎螺丝扭矩' },
        { id: 'mw_test_drive',         label: 'Test drive completed / 已完成试车' },
      ],
    },

    {
      id: 'issues_found',
      label: 'Issues Found & Action Taken / 发现问题与处理措施',
      has_result: false,
      na_for: [],
      // 动态数组: { description, action_taken, status: 'completed'|'pending'|'monitor'|'quoted' }
    },

    {
      id: 'final_result',
      label: 'Final Test Result / 最终测试结果',
      has_result: false,
      na_for: [],
      items: [
        { id: 'fr_static',    label: 'Static inspection completed / 静态检查已完成' },
        { id: 'fr_dynamic',   label: 'Dynamic test completed / 动态测试已完成' },
        { id: 'fr_functions', label: 'All major functions tested / 主要功能均已测试' },
        { id: 'fr_ok',        label: 'Machine tested and functional / 车辆测试功能正常' },
        { id: 'fr_no_faults', label: 'No active faults after final test / 最终测试后无故障' },
      ],
      final_fields: ['ready_for_delivery', 'final_comments', 'technician', 'date', 'signature'],
    },

  ],
};
